// Downloads every image listed in scripts/image-tasks.json (generated by
// generate-image-tasks.js) into its target path under the repo root,
// creating folders as needed.
//
//   node scripts/download-images.js            # skip files that already exist
//   node scripts/download-images.js --force     # re-download everything
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const TASKS_PATH = path.join(__dirname, 'image-tasks.json');
const CONCURRENCY = 8;
const MAX_ATTEMPTS = 3;
const RETRY_DELAY_MS = 1000;

const force = process.argv.includes('--force');

const tasks = JSON.parse(fs.readFileSync(TASKS_PATH, 'utf8'));

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function downloadOne(task) {
  const outPath = path.join(ROOT, task.path);

  if (!force && fs.existsSync(outPath)) {
    return { task, status: 'skipped' };
  }

  fs.mkdirSync(path.dirname(outPath), { recursive: true });

  let lastErr;
  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    try {
      const res = await fetch(task.url);
      if (!res.ok) {
        throw new Error(`HTTP ${res.status} ${res.statusText}`);
      }
      const buf = Buffer.from(await res.arrayBuffer());
      fs.writeFileSync(outPath, buf);
      return { task, status: 'downloaded' };
    } catch (err) {
      lastErr = err;
      if (attempt < MAX_ATTEMPTS) await sleep(RETRY_DELAY_MS * attempt);
    }
  }
  return { task, status: 'failed', error: lastErr };
}

async function runPool(items, worker, concurrency) {
  const results = new Array(items.length);
  let next = 0;
  async function runNext() {
    while (next < items.length) {
      const i = next++;
      results[i] = await worker(items[i]);
    }
  }
  await Promise.all(Array.from({ length: concurrency }, runNext));
  return results;
}

async function main() {
  console.log(`Processing ${tasks.length} tasks (${force ? 'force re-download' : 'skip existing'})...`);

  let downloaded = 0;
  let skipped = 0;
  const failures = [];

  const results = await runPool(tasks, downloadOne, CONCURRENCY);
  for (const r of results) {
    if (r.status === 'downloaded') downloaded++;
    else if (r.status === 'skipped') skipped++;
    else failures.push(r);
  }

  console.log(`Downloaded: ${downloaded}, skipped (already present): ${skipped}, failed: ${failures.length}`);

  if (failures.length) {
    console.log('\nFailed:');
    for (const f of failures) {
      console.log(`  ${f.task.url} -> ${f.task.path}: ${f.error && f.error.message}`);
    }
    process.exitCode = 1;
  }
}

main();
